/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPlacesRouteImport } from './routes/_app.places'
import { Route as AppPeopleRouteImport } from './routes/_app.people'
import { Route as AppMemoriesRouteImport } from './routes/_app.memories'
import { Route as AppPlaceIdRouteImport } from './routes/_app.place.$id'
import { Route as AppPersonIdRouteImport } from './routes/_app.person.$id'
import { Route as AppMemoryIdRouteImport } from './routes/_app.memory.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlacesRoute = AppPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoriesRoute = AppMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaceIdRoute = AppPlaceIdRouteImport.update({
  id: '/place/$id',
  path: '/place/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonIdRoute = AppPersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryIdRoute = AppMemoryIdRouteImport.update({
  id: '/memory/$id',
  path: '/memory/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/memories': typeof AppMemoriesRoute
  '/people': typeof AppPeopleRoute
  '/places': typeof AppPlacesRoute
  '/profile': typeof AppProfileRoute
  '/memory/$id': typeof AppMemoryIdRoute
  '/person/$id': typeof AppPersonIdRoute
  '/place/$id': typeof AppPlaceIdRoute
}
export interface FileRoutesByTo {
  '/memories': typeof AppMemoriesRoute
  '/people': typeof AppPeopleRoute
  '/places': typeof AppPlacesRoute
  '/profile': typeof AppProfileRoute
  '/': typeof AppIndexRoute
  '/memory/$id': typeof AppMemoryIdRoute
  '/person/$id': typeof AppPersonIdRoute
  '/place/$id': typeof AppPlaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/memories': typeof AppMemoriesRoute
  '/_app/people': typeof AppPeopleRoute
  '/_app/places': typeof AppPlacesRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/': typeof AppIndexRoute
  '/_app/memory/$id': typeof AppMemoryIdRoute
  '/_app/person/$id': typeof AppPersonIdRoute
  '/_app/place/$id': typeof AppPlaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/memories'
    | '/people'
    | '/places'
    | '/profile'
    | '/memory/$id'
    | '/person/$id'
    | '/place/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/memories'
    | '/people'
    | '/places'
    | '/profile'
    | '/'
    | '/memory/$id'
    | '/person/$id'
    | '/place/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_app/memories'
    | '/_app/people'
    | '/_app/places'
    | '/_app/profile'
    | '/_app/'
    | '/_app/memory/$id'
    | '/_app/person/$id'
    | '/_app/place/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/places': {
      id: '/_app/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof AppPlacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people': {
      id: '/_app/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memories': {
      id: '/_app/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof AppMemoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/place/$id': {
      id: '/_app/place/$id'
      path: '/place/$id'
      fullPath: '/place/$id'
      preLoaderRoute: typeof AppPlaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/person/$id': {
      id: '/_app/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof AppPersonIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memory/$id': {
      id: '/_app/memory/$id'
      path: '/memory/$id'
      fullPath: '/memory/$id'
      preLoaderRoute: typeof AppMemoryIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppMemoriesRoute: typeof AppMemoriesRoute
  AppPeopleRoute: typeof AppPeopleRoute
  AppPlacesRoute: typeof AppPlacesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMemoryIdRoute: typeof AppMemoryIdRoute
  AppPersonIdRoute: typeof AppPersonIdRoute
  AppPlaceIdRoute: typeof AppPlaceIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMemoriesRoute: AppMemoriesRoute,
  AppPeopleRoute: AppPeopleRoute,
  AppPlacesRoute: AppPlacesRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppMemoryIdRoute: AppMemoryIdRoute,
  AppPersonIdRoute: AppPersonIdRoute,
  AppPlaceIdRoute: AppPlaceIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
